name: Export Pluto notebooks & Deploy

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: export
    cancel-in-progress: true

permissions:
  contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Install LIKWID
              run: |
                wget http://ftp.fau.de/pub/likwid/likwid-stable.tar.gz
                mkdir likwid
                tar -xaf likwid-stable.tar.gz -C likwid --strip-components=1
                cd likwid
                make
                sudo make install
                /usr/local/bin/likwid-topology -c -C -g
                sudo modprobe msr
                /usr/local/bin/likwid-perfctr -i
                /usr/local/bin/likwid-perfctr -a

            - name: 🙌 Install Julia
              uses: julia-actions/setup-julia@v2
              with:
                  version: "1.11"

            - name: ⏱ Cache notebook states
              uses: actions/cache@v4
              with:
                path: _cache
                key: ${{ runner.os }}-pluto_state_cache-v3-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-pluto_state_cache-v3-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            - name: ⏱ Cache .julia
              uses: actions/cache@v4
              with:
                path: ~/.julia
                key: ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            - name: 🪴 Generate site
              run: julia --project=pluto-deployment-environment -e '
                  import Pkg;
                  Pkg.instantiate();

                  include("./generate.jl")'

            
            - name: 📰 Upload site generation report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                path: generation_report.html

            - name: 🚀 Deploy to GitHub Pages (main)
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  BRANCH: gh-pages
                  FOLDER: _site
                  CLEAN_EXCLUDE: |
                    previews/*

            - name: Deploy PR preview
              if: github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name # if this build is a PR build and the PR is NOT from a fork
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  BRANCH: gh-pages
                  FOLDER: _site
                  TARGET_FOLDER: "previews/PR${{ github.event.number }}" # The website preview is going to be stored in the previews subfolder
